#pragma checksum "ViewController\GenerarEstadísticas.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "CD32E1C379417933DDA3D817F2DF57EB280B43DB1406528182A8C315D871826A"
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using GestionEgresados.ViewController;
using LiveCharts.Wpf;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GestionEgresados.ViewController {
    
    
    /// <summary>
    /// GenerarEstadísticas
    /// </summary>
    public partial class GenerarEstadísticas : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "ViewController\GenerarEstadísticas.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton radioButtonGenero;
        
        #line default
        #line hidden
        
        
        #line 20 "ViewController\GenerarEstadísticas.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGenerarEstadistica;
        
        #line default
        #line hidden
        
        
        #line 22 "ViewController\GenerarEstadísticas.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton radioButtonCarrera;
        
        #line default
        #line hidden
        
        
        #line 24 "ViewController\GenerarEstadísticas.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton radioButtonNivelEstudios;
        
        #line default
        #line hidden
        
        
        #line 26 "ViewController\GenerarEstadísticas.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton radioButtonEstatusTrabajo;
        
        #line default
        #line hidden
        
        
        #line 27 "ViewController\GenerarEstadísticas.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnVolver;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/GestionEgresados;component/viewcontroller/generarestad%c3%adsticas.xaml", System.UriKind.Relative);
            
            #line 1 "ViewController\GenerarEstadísticas.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.radioButtonGenero = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 2:
            this.btnGenerarEstadistica = ((System.Windows.Controls.Button)(target));
            
            #line 20 "ViewController\GenerarEstadísticas.xaml"
            this.btnGenerarEstadistica.Click += new System.Windows.RoutedEventHandler(this.BtnGenerarReporte_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.radioButtonCarrera = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 4:
            this.radioButtonNivelEstudios = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 5:
            this.radioButtonEstatusTrabajo = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 6:
            this.btnVolver = ((System.Windows.Controls.Button)(target));
            
            #line 27 "ViewController\GenerarEstadísticas.xaml"
            this.btnVolver.Click += new System.Windows.RoutedEventHandler(this.BtnVolver_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

